# Generated by Django 3.2.7 on 2021-09-08 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('show', '0010_rename_tran_date_transaction_trans_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Live_price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_time', models.DateTimeField()),
                ('price', models.FloatField(default=0)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='show.ticker')),
            ],
        ),
    ]
