# Generated by Django 3.2.7 on 2021-09-07 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_name', models.TextField()),
                ('product_name', models.TextField()),
                ('ticker', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='show.ticker'),
        ),
    ]
