# Generated by Django 3.2.7 on 2021-09-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0002_auto_20210907_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='volume',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
