# Generated by Django 3.2.7 on 2021-09-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0003_auto_20210907_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='trans_type',
            field=models.CharField(choices=[('S', 'Sell'), ('B', 'Buy')], default='B', max_length=1),
        ),
    ]
