# Generated by Django 3.2.7 on 2021-09-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0004_ticker_trans_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticker',
            name='trans_type',
        ),
        migrations.AddField(
            model_name='transaction',
            name='trans_type',
            field=models.CharField(choices=[('S', 'Sell'), ('B', 'Buy')], default='B', max_length=1),
        ),
    ]
