# Generated by Django 3.2.7 on 2021-09-07 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0005_auto_20210907_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('div_date', models.DateField(verbose_name='dividend date')),
                ('amount', models.FloatField(default=0)),
                ('gross_per_share', models.FloatField(default=0)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='show.ticker')),
            ],
        ),
    ]
