# Generated by Django 3.2.7 on 2021-09-07 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0008_auto_20210907_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='platform',
            new_name='brokerage',
        ),
    ]
