# Generated by Django 3.2.7 on 2021-09-08 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0009_rename_platform_transaction_brokerage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='tran_date',
            new_name='trans_date',
        ),
    ]
