# Generated by Django 3.2.7 on 2021-10-08 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0010_rename_tran_date_transaction_trans_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='trans_type',
            field=models.CharField(choices=[('S', 'Sell'), ('B', 'Buy'), ('R', 'Reward')], default='B', max_length=1),
        ),
    ]
